### PR TITLE
Building forms

### PR DESCRIPTION
**Pull request by 1v4n4**
This project is meant for building some forms, both using nearly-pure HTML and then graduating to using the helper methods that Rails provide.

### CODE REVIEW

**Review by oloomoses — COMMENTED** [review]
# Invalid
**This project is invalidated because it does not have a descriptive readme. Kindly write a descriptive readme as per the [requirements](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/) and ask for another review.**

_Slack: Oloo Moses_

**Review by oloomoses — CHANGES_REQUESTED** [review]
Hello team, You have done a commendable job on this project :muscle:
## Highlights
- A user can be created:heavy_check_mark: 
- An existing user can be edited :heavy_check_mark:
- Rubocop and linters configuration :heavy_check_mark:
- 
## To Improve
- [x] n the readme setup instructions. you mention `Open up the twitter clone on your localhost at`. Kindly correct this since this is not a Twitter clone project.
- [x] Yarn packages need to be installed by running the command `yarn install` for local setup. Otherwise, the app generates an error. Kindly specify this is the readme project setup instructions.
- [x] Kindly add `form` and `form_tag` forms in the views as per the [requirements](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form1.png) and they should be commented out.

## Nice to have
- [ ] It would be better to use a form partial for `new` and `edit` forms. 
- [ ] It would be better to display a list of error messages if any.

**Please make the above changes and ask for another review**

Feel free to reach me on slack or leave a comment while mentioning me and I will be happy to reply.

### Happy Coding

_Slack: Oloo Moses_

**Comment by srizzuto** [comment]
Changes made as required!

**Review by taiwo2 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED ♻️
@srizzuto Weldone for the task, however for this project to be approved few changes is required:

- [x] it is possible to create a new user in app **(covered by automated tests)** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/create_new_user.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))
- [x] it is possible to edit a user in app **(covered by automated tests)** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/edit_user.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))

- [x] Your root routes is not configured and am getting this kindly fix.


Screenshot 2021-06-04 182954

### Create action 

- [x] should be redirect_to `edit_user_path(<USER_ID>)` kindly fixed it
- [x] Kindly add `rails db:crerate and rails db:migrate ` to your Readme file under section setup

**Comment by srizzuto** [comment]
Changes made!

**Review by emmanuellekamwa — APPROVED** [review]
**STATUS: APPROVED 🎉🎉**
Hello @1v4n4. Great job on making all the requested changes 👏🏽👏🏽. Your project is approved. Good luck with the other projects and happy coding!!👨🏽‍💻👨🏽‍💻

**Pull request merged**
